hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("uwsm app -- swaync")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
    hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/scripts/gtk-theme.sh init")
    hl.exec_cmd("uwsm app -- nm-applet")
    hl.exec_cmd("uwsm app -- fcitx5 -d --replace")
    hl.exec_cmd("uwsm app -- fcitx5-remote -r")
end)

-- hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
-- hl.exec_cmd("dbus-update-activation-environment --systemd --all")
-- hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
