windowrule = float on, match:title (fcitx)
windowrule = float on, pin on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(soffice)$
windowrule = float on, match:class ^(thunar)$
windowrule = size 1000 875, match:class (thunar)
windowrule = float on, match:class (vivaldi-stable), match:title (Open Files)

layerrule = blur on, match:namespace waybar # Add blur to waybar
layerrule = blur_popups on, match:namespace waybar # Blur waybar popups too!
layerrule = ignore_alpha 0.2, match:namespace waybar # Make it so transparent parts are ignored
layerrule = blur on, match:namespace rofi
