# Config relating to git
git:
  # How branches are sorted in the local branches view.
  # One of: 'date' (default) | 'recency' | 'alphabetical'
  # Can be changed from within Lazygit with the Sort Order menu (`s`) in the branches panel.
  localBranchSortOrder: recency
  autoStageResolvedConflicts: false
